# Generated by Django 5.0.3 on 2024-03-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RockBlockMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=100)),
                ('momsn', models.IntegerField()),
                ('transmit_time', models.DateTimeField()),
                ('iridium_latitude', models.FloatField()),
                ('iridium_longitude', models.FloatField()),
                ('iridium_cep', models.IntegerField()),
                ('data', models.TextField()),
            ],
        ),
    ]
