# Generated by Django 5.0.3 on 2024-03-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rockblockmessage',
            name='iridium_cep',
            field=models.FloatField(),
        ),
    ]
