# Generated by Django 5.0.3 on 2024-09-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0006_rockblockmessage2_doa'),
    ]

    operations = [
        migrations.CreateModel(
            name='RockBlockMessageDepth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=100)),
                ('momsn', models.IntegerField()),
                ('transmit_time', models.TextField()),
                ('iridium_latitude', models.FloatField()),
                ('iridium_longitude', models.FloatField()),
                ('iridium_cep', models.FloatField()),
                ('data', models.TextField()),
                ('header', models.TextField()),
                ('doa', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
